@extends('college.layout')
@section('content')
<section class="college-section"><div class="college-shell">
@if($page==='departments')
@include('college.programmes')
<p class="college-note">Branches reflect the current portal configuration. Confirm current course availability, intake and eligibility with the college.</p>
@elseif($page==='programme')
<div class="college-split"><article class="college-card programme-{{ strtolower($programme['code']) }}"><span class="college-badge">{{ $programme['code'] }}</span><h2>Your academic resources</h2><p>{{ $programme['intro'] }}</p><div class="college-actions"><a class="college-button" href="{{ route('portal.outbound','syllabus') }}">Official syllabus</a><a class="college-button secondary" href="/#papers">Question papers</a><a class="college-button secondary" href="/#notes">Shared notes</a></div></article><article><h2>Before choosing a programme</h2><p>Confirm course availability, duration, entry requirements, intake, approved fees and facilities with the college. The subject catalogue does not replace current admission documents.</p><a href="/admissions" class="college-text-link">Admission guidance ↗</a></article></div>
@elseif($page==='admissions')
<div class="college-split"><article><h2>Plan your application</h2><ol class="college-checklist"><li>Explore the branches in the academic catalogue.</li><li>Confirm current eligibility and admission dates.</li><li>Ask for the official application channel and document checklist.</li><li>Follow the confirmed process for verification, payment and enrolment.</li></ol><a href="/contact" class="college-button">Ask about admissions ↗</a></article><article class="college-card" id="fees"><h2>Fees &amp; financial support</h2><p>A verified fee schedule is not available on this portal. Contact the college for approved fees, payment instructions and scholarship eligibility before making a payment.</p><h3>Dates &amp; documents</h3><p>Application dates and the required documents must be confirmed for the current admission cycle.</p></article></div>
@elseif($page==='about')
<div class="college-split"><div><h2>Knowledge, skills and a better future.</h2><p>Government Polytechnic College, Shivpuri is a government technical institution. This portal brings together academic resources, student and faculty access, and moderated contributions.</p><h3>Academic connections</h3><p>The existing college information identifies AICTE approval and RGPV affiliation. Ask the college for current documents.</p><a class="college-text-link" href="/departments">Explore the academic catalogue ↗</a></div><figure class="college-campus"><img src="/assets/gpcs-campus.webp" srcset="/assets/gpcs-campus-480.webp 480w, /assets/gpcs-campus-800.webp 800w, /assets/gpcs-campus.webp 1169w" sizes="(max-width: 768px) calc(100vw - 32px), 50vw" width="1169" height="912" alt="Government Polytechnic College, Shivpuri campus" decoding="async"><figcaption>{{ config('college.address') }}</figcaption></figure></div>
@elseif($page==='gallery' || $page==='facilities')
<div class="college-split"><figure class="college-campus"><img src="/assets/gpcs-campus.webp" srcset="/assets/gpcs-campus-480.webp 480w, /assets/gpcs-campus-800.webp 800w, /assets/gpcs-campus.webp 1169w" sizes="(max-width: 768px) calc(100vw - 32px), 50vw" width="1169" height="912" alt="Government Polytechnic College, Shivpuri campus" decoding="async"><figcaption>Campus photograph from the existing portal</figcaption></figure><div><h2>Explore college life</h2><p>The existing gallery groups college-related photographs into campus, events, labs and workshops, students and staff, sports and cultural activities, and projects.</p><p>Use your portal account to view the approved gallery or contribute images for review.</p><a href="/#gallery" class="college-button">Open portal gallery ↗</a><p class="college-note">Contact the college to confirm the current facilities available to your programme.</p></div></div>
@elseif($page==='contact')
<div class="college-split"><article><h2>Find us in Shivpuri</h2><address>{{ config('college.address') }}</address><p>Use the secure portal contact form for enquiries. A verified public helpline and email address are not available in the current source.</p><div class="college-actions"><a href="/#contact" class="college-button">Send a message</a><a href="https://www.google.com/maps/search/?api=1&amp;query=Government+Polytechnic+College+Shivpuri" target="_blank" rel="noopener noreferrer" class="college-button secondary">Open campus map ↗</a></div></article><div class="college-map" aria-label="Campus location"><span class="college-eyebrow">Campus location</span><h2>Shivpuri</h2><p>Chhatri Road · Madhya Pradesh</p><p>Open the map to locate the college and plan your visit.</p></div></div>
@elseif($page==='faq')
@include('college.faq')
@elseif($page==='faculty')
<div class="college-empty"><h2>Faculty information</h2><p>A verified public faculty directory is not available in the current source. Personal registration data is kept private. Ask the college for its current department-wise faculty directory.</p><a href="/contact" class="college-button">Contact the college</a></div><div class="college-actions"><a href="/#login" class="college-text-link">Faculty Login / Registration ↗</a></div>
@elseif($page==='placements')
<div class="college-empty"><h2>Verified placement information</h2><p>Current placement figures, recruiter lists and alumni stories have not been supplied. Request an official placement report and career guidance from the college.</p><a href="/contact" class="college-button">Placement enquiries</a></div>
@elseif($page==='notices')
<div class="college-cards two"><article class="college-empty"><h2>Notices &amp; events</h2><p>A verified public notice feed is not available here. Contact the college for official announcements and event information.</p><a href="/contact" class="college-text-link">Ask the college ↗</a></article><article class="college-card" id="timetable"><h2>Academic timetable</h2><p>Confirm the latest department and semester timetable with the college before planning classes or examinations.</p><a href="{{ route('portal.outbound','main-result') }}" class="college-text-link">Official results ↗</a></article></div>
@endif
</div></section>
@endsection
